# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS Assignment1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SDWebImage'
  # Pods for iOS Assignment1

  target 'iOS Assignment1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS Assignment1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
